version: '3.8'

services:
  M10web:
    build: .
    container_name: M10web
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    depends_on:
      - database_M10web
    environment:
      - DATABASE_URL=mysql://root:root@database_M10web:3306/M10web?reconnect=true

  database_M10web:
    container_name: database_M10web
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3333:3306'
    volumes:
      - pgdata:/data/mysql
    env_file:
      - .env

volumes:
  pgdata: ~